### ISSUE TITLE
 envire_2D_structure_widget, which is a DEP_PKGCONFIG in /src/ not found. Where is the package defined?

### ISSUE THREAD

**Issue by jimaldon** [envire/envire-envire_visualizer#1]
While building with autoproj, CMake complains that 

`package 'envire_2D_structure_widget' not found.
`

**Comment by arneboe** [comment]
`envire_2D_structure_widget` is defined in `ènvire/envire_core/viz` in the EnvireVisualizer branch. The branch should be checked out by default as it is defined in the entern overrides.  Are you using the entern buildconf?

**Comment by jimaldon** [comment]
No I'm using the envire buildconf, so it makes sense that it checkout out the master branch

**Comment by jimaldon** [comment]
UPDATE:
@arneboe  I tried using the branch you mentioned to compile envire_core and it executed fine. But envire_visulaized still doesn't compile. It gives errors like these:

`envire_visualizer/src/EnvireVisualizerWindow.cpp:89:27: error: 'class vizkit3d::Vizkit3DWidget' has no member named 'clear'
       window->Vizkit3DWidget->clear();
`

**Comment by arneboe** [comment]
That is because we are using a different version of vizkit3d in entern. You can get it from github.com/planthaber/gui-vizkit3d. We are using the branch osgviz which depends on osgViz.

I guess all those dependencies should be in the envire buildconf, not just in entern. I'll discuss it today in the envire meeting and update the buildconf.
